/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProspectData = IDL.Record({
  'title' : IDL.Text,
  'recentContext' : IDL.Text,
  'company' : IDL.Text,
  'painPoints' : IDL.Vec(IDL.Text),
  'companySize' : IDL.Nat,
  'lastName' : IDL.Text,
  'industry' : IDL.Text,
  'firstName' : IDL.Text,
});
export const OfferData = IDL.Record({
  'targetOutcome' : IDL.Text,
  'valueProposition' : IDL.Text,
  'productDescription' : IDL.Text,
});
export const EmailVariant = IDL.Record({
  'subject' : IDL.Text,
  'body' : IDL.Text,
});
export const AgentResult = IDL.Record({
  'variantA' : EmailVariant,
  'variantB' : EmailVariant,
});
export const GenerateEmailsError = IDL.Variant({
  'httpOutcallFailed' : IDL.Text,
  'aiFailed' : IDL.Text,
});
export const GenerateEmailsResult = IDL.Variant({
  'ok' : AgentResult,
  'err' : GenerateEmailsError,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'generateEmails' : IDL.Func(
      [ProspectData, OfferData, IDL.Text],
      [GenerateEmailsResult],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProspectData = IDL.Record({
    'title' : IDL.Text,
    'recentContext' : IDL.Text,
    'company' : IDL.Text,
    'painPoints' : IDL.Vec(IDL.Text),
    'companySize' : IDL.Nat,
    'lastName' : IDL.Text,
    'industry' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const OfferData = IDL.Record({
    'targetOutcome' : IDL.Text,
    'valueProposition' : IDL.Text,
    'productDescription' : IDL.Text,
  });
  const EmailVariant = IDL.Record({ 'subject' : IDL.Text, 'body' : IDL.Text });
  const AgentResult = IDL.Record({
    'variantA' : EmailVariant,
    'variantB' : EmailVariant,
  });
  const GenerateEmailsError = IDL.Variant({
    'httpOutcallFailed' : IDL.Text,
    'aiFailed' : IDL.Text,
  });
  const GenerateEmailsResult = IDL.Variant({
    'ok' : AgentResult,
    'err' : GenerateEmailsError,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'generateEmails' : IDL.Func(
        [ProspectData, OfferData, IDL.Text],
        [GenerateEmailsResult],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };